// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Q9n95QRH2UfO_I1H4JbXRSxZ9nYsCL0',
    appId: '1:1090559860924:web:44e9c749de2dd6d57fb0b9',
    messagingSenderId: '1090559860924',
    projectId: 'tongate-4d2a0',
    authDomain: 'tongate-4d2a0.firebaseapp.com',
    storageBucket: 'tongate-4d2a0.appspot.com',
    measurementId: 'G-1VYB3R57NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAOFKiWlDCFDCwbynhUGugZvJ6M0_VHs',
    appId: '1:1090559860924:android:3790468aae9da66d7fb0b9',
    messagingSenderId: '1090559860924',
    projectId: 'tongate-4d2a0',
    storageBucket: 'tongate-4d2a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBLGmurVOy25K24GhwJ1mxLR7YnWzhy8',
    appId: '1:1090559860924:ios:1bc2d26c6e3b4cc67fb0b9',
    messagingSenderId: '1090559860924',
    projectId: 'tongate-4d2a0',
    storageBucket: 'tongate-4d2a0.appspot.com',
    iosBundleId: 'com.pixeldat.tongate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjBLGmurVOy25K24GhwJ1mxLR7YnWzhy8',
    appId: '1:1090559860924:ios:1bc2d26c6e3b4cc67fb0b9',
    messagingSenderId: '1090559860924',
    projectId: 'tongate-4d2a0',
    storageBucket: 'tongate-4d2a0.appspot.com',
    iosBundleId: 'com.pixeldat.tongate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Q9n95QRH2UfO_I1H4JbXRSxZ9nYsCL0',
    appId: '1:1090559860924:web:f4ed24662f196b077fb0b9',
    messagingSenderId: '1090559860924',
    projectId: 'tongate-4d2a0',
    authDomain: 'tongate-4d2a0.firebaseapp.com',
    storageBucket: 'tongate-4d2a0.appspot.com',
    measurementId: 'G-RCQBL0QPVX',
  );
}
